# Generated by Django 5.2.7 on 2025-10-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partita_doppia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='ragione_sociale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
