# Generated by Django 5.2.7 on 2025-10-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anagrafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('S', 'Socio'), ('V', 'Volontario'), ('C', 'Consigliere'), ('F', 'Fornitore')], max_length=1)),
                ('cognome', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('sesso', models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1)),
                ('data_di_nascita', models.DateField()),
                ('luogo_di_nascita', models.CharField(max_length=255)),
                ('ragione_sociale', models.CharField(max_length=255)),
                ('codice_fiscale', models.CharField(blank=True, editable=False, max_length=16, null=True)),
                ('partita_iva', models.CharField(blank=True, max_length=20, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Anagrafiche',
            },
        ),
    ]
